// Copyright 2025, compose-miuix-ui contributors
// SPDX-License-Identifier: Apache-2.0

package utils

import androidx.compose.ui.graphics.vector.ImageVector
import io.elyon.kmp.icon.ElyonIcons
import io.elyon.kmp.icon.extended.Add
import io.elyon.kmp.icon.extended.AddCircle
import io.elyon.kmp.icon.extended.AddFolder
import io.elyon.kmp.icon.extended.Alarm
import io.elyon.kmp.icon.extended.Album
import io.elyon.kmp.icon.extended.All
import io.elyon.kmp.icon.extended.Answer
import io.elyon.kmp.icon.extended.AppRecording
import io.elyon.kmp.icon.extended.Back
import io.elyon.kmp.icon.extended.Background
import io.elyon.kmp.icon.extended.Backup
import io.elyon.kmp.icon.extended.BankCards
import io.elyon.kmp.icon.extended.Blocklist
import io.elyon.kmp.icon.extended.CallRecording
import io.elyon.kmp.icon.extended.Carrier
import io.elyon.kmp.icon.extended.ChevronBackward
import io.elyon.kmp.icon.extended.ChevronForward
import io.elyon.kmp.icon.extended.Clear
import io.elyon.kmp.icon.extended.Close
import io.elyon.kmp.icon.extended.Close2
import io.elyon.kmp.icon.extended.CloudFill
import io.elyon.kmp.icon.extended.Community
import io.elyon.kmp.icon.extended.Contacts
import io.elyon.kmp.icon.extended.ContactsBook
import io.elyon.kmp.icon.extended.ContactsCircle
import io.elyon.kmp.icon.extended.ConvertFile
import io.elyon.kmp.icon.extended.Copy
import io.elyon.kmp.icon.extended.Create
import io.elyon.kmp.icon.extended.Cut
import io.elyon.kmp.icon.extended.Delete
import io.elyon.kmp.icon.extended.Download
import io.elyon.kmp.icon.extended.Edit
import io.elyon.kmp.icon.extended.Email
import io.elyon.kmp.icon.extended.ExpandLess
import io.elyon.kmp.icon.extended.ExpandMore
import io.elyon.kmp.icon.extended.Favorites
import io.elyon.kmp.icon.extended.FavoritesFill
import io.elyon.kmp.icon.extended.File
import io.elyon.kmp.icon.extended.FileDownloads
import io.elyon.kmp.icon.extended.Filter
import io.elyon.kmp.icon.extended.Folder
import io.elyon.kmp.icon.extended.FolderFill
import io.elyon.kmp.icon.extended.Forward
import io.elyon.kmp.icon.extended.GridView
import io.elyon.kmp.icon.extended.Help
import io.elyon.kmp.icon.extended.Hide
import io.elyon.kmp.icon.extended.Home
import io.elyon.kmp.icon.extended.HorizontalSplit
import io.elyon.kmp.icon.extended.Image
import io.elyon.kmp.icon.extended.Import
import io.elyon.kmp.icon.extended.Info
import io.elyon.kmp.icon.extended.Layers
import io.elyon.kmp.icon.extended.Link
import io.elyon.kmp.icon.extended.ListView
import io.elyon.kmp.icon.extended.Location
import io.elyon.kmp.icon.extended.Lock
import io.elyon.kmp.icon.extended.MapAlbum
import io.elyon.kmp.icon.extended.Merge
import io.elyon.kmp.icon.extended.Messages
import io.elyon.kmp.icon.extended.Mic
import io.elyon.kmp.icon.extended.MicSlash
import io.elyon.kmp.icon.extended.MindMap
import io.elyon.kmp.icon.extended.Months
import io.elyon.kmp.icon.extended.More
import io.elyon.kmp.icon.extended.MoreCircle
import io.elyon.kmp.icon.extended.MoveFile
import io.elyon.kmp.icon.extended.Music
import io.elyon.kmp.icon.extended.Notes
import io.elyon.kmp.icon.extended.NotesFill
import io.elyon.kmp.icon.extended.Ok
import io.elyon.kmp.icon.extended.Paste
import io.elyon.kmp.icon.extended.Pause
import io.elyon.kmp.icon.extended.Phone
import io.elyon.kmp.icon.extended.Photos
import io.elyon.kmp.icon.extended.Pin
import io.elyon.kmp.icon.extended.Play
import io.elyon.kmp.icon.extended.Playlist
import io.elyon.kmp.icon.extended.Promotions
import io.elyon.kmp.icon.extended.Recent
import io.elyon.kmp.icon.extended.Recording
import io.elyon.kmp.icon.extended.RecordingTape
import io.elyon.kmp.icon.extended.Redo
import io.elyon.kmp.icon.extended.Refresh
import io.elyon.kmp.icon.extended.Remove
import io.elyon.kmp.icon.extended.RemoveContact
import io.elyon.kmp.icon.extended.Rename
import io.elyon.kmp.icon.extended.Replace
import io.elyon.kmp.icon.extended.Reply
import io.elyon.kmp.icon.extended.ReplyAll
import io.elyon.kmp.icon.extended.Report
import io.elyon.kmp.icon.extended.Reset
import io.elyon.kmp.icon.extended.RotateLeft
import io.elyon.kmp.icon.extended.Scan
import io.elyon.kmp.icon.extended.ScreenCapture
import io.elyon.kmp.icon.extended.ScreenMirroring
import io.elyon.kmp.icon.extended.Search
import io.elyon.kmp.icon.extended.SearchDevice
import io.elyon.kmp.icon.extended.SelectAll
import io.elyon.kmp.icon.extended.Send
import io.elyon.kmp.icon.extended.Settings
import io.elyon.kmp.icon.extended.Share
import io.elyon.kmp.icon.extended.Show
import io.elyon.kmp.icon.extended.Sidebar
import io.elyon.kmp.icon.extended.Sort
import io.elyon.kmp.icon.extended.Stopwatch
import io.elyon.kmp.icon.extended.Store
import io.elyon.kmp.icon.extended.Tasks
import io.elyon.kmp.icon.extended.Th1
import io.elyon.kmp.icon.extended.Th10
import io.elyon.kmp.icon.extended.Th11
import io.elyon.kmp.icon.extended.Th12
import io.elyon.kmp.icon.extended.Th13
import io.elyon.kmp.icon.extended.Th14
import io.elyon.kmp.icon.extended.Th15
import io.elyon.kmp.icon.extended.Th16
import io.elyon.kmp.icon.extended.Th17
import io.elyon.kmp.icon.extended.Th18
import io.elyon.kmp.icon.extended.Th19
import io.elyon.kmp.icon.extended.Th2
import io.elyon.kmp.icon.extended.Th20
import io.elyon.kmp.icon.extended.Th21
import io.elyon.kmp.icon.extended.Th22
import io.elyon.kmp.icon.extended.Th23
import io.elyon.kmp.icon.extended.Th24
import io.elyon.kmp.icon.extended.Th25
import io.elyon.kmp.icon.extended.Th26
import io.elyon.kmp.icon.extended.Th27
import io.elyon.kmp.icon.extended.Th28
import io.elyon.kmp.icon.extended.Th29
import io.elyon.kmp.icon.extended.Th3
import io.elyon.kmp.icon.extended.Th30
import io.elyon.kmp.icon.extended.Th31
import io.elyon.kmp.icon.extended.Th4
import io.elyon.kmp.icon.extended.Th5
import io.elyon.kmp.icon.extended.Th6
import io.elyon.kmp.icon.extended.Th7
import io.elyon.kmp.icon.extended.Th8
import io.elyon.kmp.icon.extended.Th9
import io.elyon.kmp.icon.extended.Theme
import io.elyon.kmp.icon.extended.Timer
import io.elyon.kmp.icon.extended.TopDownloads
import io.elyon.kmp.icon.extended.Translate
import io.elyon.kmp.icon.extended.Trim
import io.elyon.kmp.icon.extended.Tune
import io.elyon.kmp.icon.extended.Undo
import io.elyon.kmp.icon.extended.Unlock
import io.elyon.kmp.icon.extended.Unpin
import io.elyon.kmp.icon.extended.Update
import io.elyon.kmp.icon.extended.UploadCloud
import io.elyon.kmp.icon.extended.VerticalSplit
import io.elyon.kmp.icon.extended.VolumeOff
import io.elyon.kmp.icon.extended.VolumeUp
import io.elyon.kmp.icon.extended.Weeks
import io.elyon.kmp.icon.extended.WorldClock
import io.elyon.kmp.icon.extended.Years
import io.elyon.kmp.icon.extended.ZoomOut

val ElyonIcons.All: Map<String, List<ImageVector>>
    get() = mapOf(
        "Light" to listOf(
            ElyonIcons.Light.Add,
            ElyonIcons.Light.AddCircle,
            ElyonIcons.Light.AddFolder,
            ElyonIcons.Light.Alarm,
            ElyonIcons.Light.Album,
            ElyonIcons.Light.All,
            ElyonIcons.Light.Answer,
            ElyonIcons.Light.AppRecording,
            ElyonIcons.Light.Back,
            ElyonIcons.Light.Background,
            ElyonIcons.Light.Backup,
            ElyonIcons.Light.BankCards,
            ElyonIcons.Light.Blocklist,
            ElyonIcons.Light.CallRecording,
            ElyonIcons.Light.Carrier,
            ElyonIcons.Light.ChevronBackward,
            ElyonIcons.Light.ChevronForward,
            ElyonIcons.Light.Clear,
            ElyonIcons.Light.Close,
            ElyonIcons.Light.Close2,
            ElyonIcons.Light.CloudFill,
            ElyonIcons.Light.Community,
            ElyonIcons.Light.Contacts,
            ElyonIcons.Light.ContactsBook,
            ElyonIcons.Light.ContactsCircle,
            ElyonIcons.Light.ConvertFile,
            ElyonIcons.Light.Copy,
            ElyonIcons.Light.Create,
            ElyonIcons.Light.Cut,
            ElyonIcons.Light.Delete,
            ElyonIcons.Light.Download,
            ElyonIcons.Light.Edit,
            ElyonIcons.Light.Email,
            ElyonIcons.Light.ExpandLess,
            ElyonIcons.Light.ExpandMore,
            ElyonIcons.Light.Favorites,
            ElyonIcons.Light.FavoritesFill,
            ElyonIcons.Light.File,
            ElyonIcons.Light.FileDownloads,
            ElyonIcons.Light.Filter,
            ElyonIcons.Light.Folder,
            ElyonIcons.Light.FolderFill,
            ElyonIcons.Light.Forward,
            ElyonIcons.Light.GridView,
            ElyonIcons.Light.Help,
            ElyonIcons.Light.Hide,
            ElyonIcons.Light.Home,
            ElyonIcons.Light.HorizontalSplit,
            ElyonIcons.Light.Image,
            ElyonIcons.Light.Import,
            ElyonIcons.Light.Info,
            ElyonIcons.Light.Layers,
            ElyonIcons.Light.Link,
            ElyonIcons.Light.ListView,
            ElyonIcons.Light.Location,
            ElyonIcons.Light.Lock,
            ElyonIcons.Light.MapAlbum,
            ElyonIcons.Light.Merge,
            ElyonIcons.Light.Messages,
            ElyonIcons.Light.Mic,
            ElyonIcons.Light.MicSlash,
            ElyonIcons.Light.MindMap,
            ElyonIcons.Light.Months,
            ElyonIcons.Light.More,
            ElyonIcons.Light.MoreCircle,
            ElyonIcons.Light.MoveFile,
            ElyonIcons.Light.Music,
            ElyonIcons.Light.Notes,
            ElyonIcons.Light.NotesFill,
            ElyonIcons.Light.Ok,
            ElyonIcons.Light.Paste,
            ElyonIcons.Light.Pause,
            ElyonIcons.Light.Phone,
            ElyonIcons.Light.Photos,
            ElyonIcons.Light.Pin,
            ElyonIcons.Light.Play,
            ElyonIcons.Light.Playlist,
            ElyonIcons.Light.Promotions,
            ElyonIcons.Light.Recent,
            ElyonIcons.Light.Recording,
            ElyonIcons.Light.RecordingTape,
            ElyonIcons.Light.Redo,
            ElyonIcons.Light.Refresh,
            ElyonIcons.Light.Remove,
            ElyonIcons.Light.RemoveContact,
            ElyonIcons.Light.Rename,
            ElyonIcons.Light.Replace,
            ElyonIcons.Light.Reply,
            ElyonIcons.Light.ReplyAll,
            ElyonIcons.Light.Report,
            ElyonIcons.Light.Reset,
            ElyonIcons.Light.RotateLeft,
            ElyonIcons.Light.Scan,
            ElyonIcons.Light.ScreenCapture,
            ElyonIcons.Light.ScreenMirroring,
            ElyonIcons.Light.Search,
            ElyonIcons.Light.SearchDevice,
            ElyonIcons.Light.SelectAll,
            ElyonIcons.Light.Send,
            ElyonIcons.Light.Settings,
            ElyonIcons.Light.Share,
            ElyonIcons.Light.Show,
            ElyonIcons.Light.Sidebar,
            ElyonIcons.Light.Sort,
            ElyonIcons.Light.Stopwatch,
            ElyonIcons.Light.Store,
            ElyonIcons.Light.Tasks,
            ElyonIcons.Light.Th1,
            ElyonIcons.Light.Th10,
            ElyonIcons.Light.Th11,
            ElyonIcons.Light.Th12,
            ElyonIcons.Light.Th13,
            ElyonIcons.Light.Th14,
            ElyonIcons.Light.Th15,
            ElyonIcons.Light.Th16,
            ElyonIcons.Light.Th17,
            ElyonIcons.Light.Th18,
            ElyonIcons.Light.Th19,
            ElyonIcons.Light.Th2,
            ElyonIcons.Light.Th20,
            ElyonIcons.Light.Th21,
            ElyonIcons.Light.Th22,
            ElyonIcons.Light.Th23,
            ElyonIcons.Light.Th24,
            ElyonIcons.Light.Th25,
            ElyonIcons.Light.Th26,
            ElyonIcons.Light.Th27,
            ElyonIcons.Light.Th28,
            ElyonIcons.Light.Th29,
            ElyonIcons.Light.Th3,
            ElyonIcons.Light.Th30,
            ElyonIcons.Light.Th31,
            ElyonIcons.Light.Th4,
            ElyonIcons.Light.Th5,
            ElyonIcons.Light.Th6,
            ElyonIcons.Light.Th7,
            ElyonIcons.Light.Th8,
            ElyonIcons.Light.Th9,
            ElyonIcons.Light.Theme,
            ElyonIcons.Light.Timer,
            ElyonIcons.Light.TopDownloads,
            ElyonIcons.Light.Translate,
            ElyonIcons.Light.Trim,
            ElyonIcons.Light.Tune,
            ElyonIcons.Light.Undo,
            ElyonIcons.Light.Unlock,
            ElyonIcons.Light.Unpin,
            ElyonIcons.Light.Update,
            ElyonIcons.Light.UploadCloud,
            ElyonIcons.Light.VerticalSplit,
            ElyonIcons.Light.VolumeOff,
            ElyonIcons.Light.VolumeUp,
            ElyonIcons.Light.Weeks,
            ElyonIcons.Light.WorldClock,
            ElyonIcons.Light.Years,
            ElyonIcons.Light.ZoomOut,
        ),
        "Normal" to listOf(
            ElyonIcons.Normal.Add,
            ElyonIcons.Normal.AddCircle,
            ElyonIcons.Normal.AddFolder,
            ElyonIcons.Normal.Alarm,
            ElyonIcons.Normal.Album,
            ElyonIcons.Normal.All,
            ElyonIcons.Normal.Answer,
            ElyonIcons.Normal.AppRecording,
            ElyonIcons.Normal.Back,
            ElyonIcons.Normal.Background,
            ElyonIcons.Normal.Backup,
            ElyonIcons.Normal.BankCards,
            ElyonIcons.Normal.Blocklist,
            ElyonIcons.Normal.CallRecording,
            ElyonIcons.Normal.Carrier,
            ElyonIcons.Normal.ChevronBackward,
            ElyonIcons.Normal.ChevronForward,
            ElyonIcons.Normal.Clear,
            ElyonIcons.Normal.Close,
            ElyonIcons.Normal.Close2,
            ElyonIcons.Normal.CloudFill,
            ElyonIcons.Normal.Community,
            ElyonIcons.Normal.Contacts,
            ElyonIcons.Normal.ContactsBook,
            ElyonIcons.Normal.ContactsCircle,
            ElyonIcons.Normal.ConvertFile,
            ElyonIcons.Normal.Copy,
            ElyonIcons.Normal.Create,
            ElyonIcons.Normal.Cut,
            ElyonIcons.Normal.Delete,
            ElyonIcons.Normal.Download,
            ElyonIcons.Normal.Edit,
            ElyonIcons.Normal.Email,
            ElyonIcons.Normal.ExpandLess,
            ElyonIcons.Normal.ExpandMore,
            ElyonIcons.Normal.Favorites,
            ElyonIcons.Normal.FavoritesFill,
            ElyonIcons.Normal.File,
            ElyonIcons.Normal.FileDownloads,
            ElyonIcons.Normal.Filter,
            ElyonIcons.Normal.Folder,
            ElyonIcons.Normal.FolderFill,
            ElyonIcons.Normal.Forward,
            ElyonIcons.Normal.GridView,
            ElyonIcons.Normal.Help,
            ElyonIcons.Normal.Hide,
            ElyonIcons.Normal.Home,
            ElyonIcons.Normal.HorizontalSplit,
            ElyonIcons.Normal.Image,
            ElyonIcons.Normal.Import,
            ElyonIcons.Normal.Info,
            ElyonIcons.Normal.Layers,
            ElyonIcons.Normal.Link,
            ElyonIcons.Normal.ListView,
            ElyonIcons.Normal.Location,
            ElyonIcons.Normal.Lock,
            ElyonIcons.Normal.MapAlbum,
            ElyonIcons.Normal.Merge,
            ElyonIcons.Normal.Messages,
            ElyonIcons.Normal.Mic,
            ElyonIcons.Normal.MicSlash,
            ElyonIcons.Normal.MindMap,
            ElyonIcons.Normal.Months,
            ElyonIcons.Normal.More,
            ElyonIcons.Normal.MoreCircle,
            ElyonIcons.Normal.MoveFile,
            ElyonIcons.Normal.Music,
            ElyonIcons.Normal.Notes,
            ElyonIcons.Normal.NotesFill,
            ElyonIcons.Normal.Ok,
            ElyonIcons.Normal.Paste,
            ElyonIcons.Normal.Pause,
            ElyonIcons.Normal.Phone,
            ElyonIcons.Normal.Photos,
            ElyonIcons.Normal.Pin,
            ElyonIcons.Normal.Play,
            ElyonIcons.Normal.Playlist,
            ElyonIcons.Normal.Promotions,
            ElyonIcons.Normal.Recent,
            ElyonIcons.Normal.Recording,
            ElyonIcons.Normal.RecordingTape,
            ElyonIcons.Normal.Redo,
            ElyonIcons.Normal.Refresh,
            ElyonIcons.Normal.Remove,
            ElyonIcons.Normal.RemoveContact,
            ElyonIcons.Normal.Rename,
            ElyonIcons.Normal.Replace,
            ElyonIcons.Normal.Reply,
            ElyonIcons.Normal.ReplyAll,
            ElyonIcons.Normal.Report,
            ElyonIcons.Normal.Reset,
            ElyonIcons.Normal.RotateLeft,
            ElyonIcons.Normal.Scan,
            ElyonIcons.Normal.ScreenCapture,
            ElyonIcons.Normal.ScreenMirroring,
            ElyonIcons.Normal.Search,
            ElyonIcons.Normal.SearchDevice,
            ElyonIcons.Normal.SelectAll,
            ElyonIcons.Normal.Send,
            ElyonIcons.Normal.Settings,
            ElyonIcons.Normal.Share,
            ElyonIcons.Normal.Show,
            ElyonIcons.Normal.Sidebar,
            ElyonIcons.Normal.Sort,
            ElyonIcons.Normal.Stopwatch,
            ElyonIcons.Normal.Store,
            ElyonIcons.Normal.Tasks,
            ElyonIcons.Normal.Th1,
            ElyonIcons.Normal.Th10,
            ElyonIcons.Normal.Th11,
            ElyonIcons.Normal.Th12,
            ElyonIcons.Normal.Th13,
            ElyonIcons.Normal.Th14,
            ElyonIcons.Normal.Th15,
            ElyonIcons.Normal.Th16,
            ElyonIcons.Normal.Th17,
            ElyonIcons.Normal.Th18,
            ElyonIcons.Normal.Th19,
            ElyonIcons.Normal.Th2,
            ElyonIcons.Normal.Th20,
            ElyonIcons.Normal.Th21,
            ElyonIcons.Normal.Th22,
            ElyonIcons.Normal.Th23,
            ElyonIcons.Normal.Th24,
            ElyonIcons.Normal.Th25,
            ElyonIcons.Normal.Th26,
            ElyonIcons.Normal.Th27,
            ElyonIcons.Normal.Th28,
            ElyonIcons.Normal.Th29,
            ElyonIcons.Normal.Th3,
            ElyonIcons.Normal.Th30,
            ElyonIcons.Normal.Th31,
            ElyonIcons.Normal.Th4,
            ElyonIcons.Normal.Th5,
            ElyonIcons.Normal.Th6,
            ElyonIcons.Normal.Th7,
            ElyonIcons.Normal.Th8,
            ElyonIcons.Normal.Th9,
            ElyonIcons.Normal.Theme,
            ElyonIcons.Normal.Timer,
            ElyonIcons.Normal.TopDownloads,
            ElyonIcons.Normal.Translate,
            ElyonIcons.Normal.Trim,
            ElyonIcons.Normal.Tune,
            ElyonIcons.Normal.Undo,
            ElyonIcons.Normal.Unlock,
            ElyonIcons.Normal.Unpin,
            ElyonIcons.Normal.Update,
            ElyonIcons.Normal.UploadCloud,
            ElyonIcons.Normal.VerticalSplit,
            ElyonIcons.Normal.VolumeOff,
            ElyonIcons.Normal.VolumeUp,
            ElyonIcons.Normal.Weeks,
            ElyonIcons.Normal.WorldClock,
            ElyonIcons.Normal.Years,
            ElyonIcons.Normal.ZoomOut,
        ),
        "Regular" to listOf(
            ElyonIcons.Regular.Add,
            ElyonIcons.Regular.AddCircle,
            ElyonIcons.Regular.AddFolder,
            ElyonIcons.Regular.Alarm,
            ElyonIcons.Regular.Album,
            ElyonIcons.Regular.All,
            ElyonIcons.Regular.Answer,
            ElyonIcons.Regular.AppRecording,
            ElyonIcons.Regular.Back,
            ElyonIcons.Regular.Background,
            ElyonIcons.Regular.Backup,
            ElyonIcons.Regular.BankCards,
            ElyonIcons.Regular.Blocklist,
            ElyonIcons.Regular.CallRecording,
            ElyonIcons.Regular.Carrier,
            ElyonIcons.Regular.ChevronBackward,
            ElyonIcons.Regular.ChevronForward,
            ElyonIcons.Regular.Clear,
            ElyonIcons.Regular.Close,
            ElyonIcons.Regular.Close2,
            ElyonIcons.Regular.CloudFill,
            ElyonIcons.Regular.Community,
            ElyonIcons.Regular.Contacts,
            ElyonIcons.Regular.ContactsBook,
            ElyonIcons.Regular.ContactsCircle,
            ElyonIcons.Regular.ConvertFile,
            ElyonIcons.Regular.Copy,
            ElyonIcons.Regular.Create,
            ElyonIcons.Regular.Cut,
            ElyonIcons.Regular.Delete,
            ElyonIcons.Regular.Download,
            ElyonIcons.Regular.Edit,
            ElyonIcons.Regular.Email,
            ElyonIcons.Regular.ExpandLess,
            ElyonIcons.Regular.ExpandMore,
            ElyonIcons.Regular.Favorites,
            ElyonIcons.Regular.FavoritesFill,
            ElyonIcons.Regular.File,
            ElyonIcons.Regular.FileDownloads,
            ElyonIcons.Regular.Filter,
            ElyonIcons.Regular.Folder,
            ElyonIcons.Regular.FolderFill,
            ElyonIcons.Regular.Forward,
            ElyonIcons.Regular.GridView,
            ElyonIcons.Regular.Help,
            ElyonIcons.Regular.Hide,
            ElyonIcons.Regular.Home,
            ElyonIcons.Regular.HorizontalSplit,
            ElyonIcons.Regular.Image,
            ElyonIcons.Regular.Import,
            ElyonIcons.Regular.Info,
            ElyonIcons.Regular.Layers,
            ElyonIcons.Regular.Link,
            ElyonIcons.Regular.ListView,
            ElyonIcons.Regular.Location,
            ElyonIcons.Regular.Lock,
            ElyonIcons.Regular.MapAlbum,
            ElyonIcons.Regular.Merge,
            ElyonIcons.Regular.Messages,
            ElyonIcons.Regular.Mic,
            ElyonIcons.Regular.MicSlash,
            ElyonIcons.Regular.MindMap,
            ElyonIcons.Regular.Months,
            ElyonIcons.Regular.More,
            ElyonIcons.Regular.MoreCircle,
            ElyonIcons.Regular.MoveFile,
            ElyonIcons.Regular.Music,
            ElyonIcons.Regular.Notes,
            ElyonIcons.Regular.NotesFill,
            ElyonIcons.Regular.Ok,
            ElyonIcons.Regular.Paste,
            ElyonIcons.Regular.Pause,
            ElyonIcons.Regular.Phone,
            ElyonIcons.Regular.Photos,
            ElyonIcons.Regular.Pin,
            ElyonIcons.Regular.Play,
            ElyonIcons.Regular.Playlist,
            ElyonIcons.Regular.Promotions,
            ElyonIcons.Regular.Recent,
            ElyonIcons.Regular.Recording,
            ElyonIcons.Regular.RecordingTape,
            ElyonIcons.Regular.Redo,
            ElyonIcons.Regular.Refresh,
            ElyonIcons.Regular.Remove,
            ElyonIcons.Regular.RemoveContact,
            ElyonIcons.Regular.Rename,
            ElyonIcons.Regular.Replace,
            ElyonIcons.Regular.Reply,
            ElyonIcons.Regular.ReplyAll,
            ElyonIcons.Regular.Report,
            ElyonIcons.Regular.Reset,
            ElyonIcons.Regular.RotateLeft,
            ElyonIcons.Regular.Scan,
            ElyonIcons.Regular.ScreenCapture,
            ElyonIcons.Regular.ScreenMirroring,
            ElyonIcons.Regular.Search,
            ElyonIcons.Regular.SearchDevice,
            ElyonIcons.Regular.SelectAll,
            ElyonIcons.Regular.Send,
            ElyonIcons.Regular.Settings,
            ElyonIcons.Regular.Share,
            ElyonIcons.Regular.Show,
            ElyonIcons.Regular.Sidebar,
            ElyonIcons.Regular.Sort,
            ElyonIcons.Regular.Stopwatch,
            ElyonIcons.Regular.Store,
            ElyonIcons.Regular.Tasks,
            ElyonIcons.Regular.Th1,
            ElyonIcons.Regular.Th10,
            ElyonIcons.Regular.Th11,
            ElyonIcons.Regular.Th12,
            ElyonIcons.Regular.Th13,
            ElyonIcons.Regular.Th14,
            ElyonIcons.Regular.Th15,
            ElyonIcons.Regular.Th16,
            ElyonIcons.Regular.Th17,
            ElyonIcons.Regular.Th18,
            ElyonIcons.Regular.Th19,
            ElyonIcons.Regular.Th2,
            ElyonIcons.Regular.Th20,
            ElyonIcons.Regular.Th21,
            ElyonIcons.Regular.Th22,
            ElyonIcons.Regular.Th23,
            ElyonIcons.Regular.Th24,
            ElyonIcons.Regular.Th25,
            ElyonIcons.Regular.Th26,
            ElyonIcons.Regular.Th27,
            ElyonIcons.Regular.Th28,
            ElyonIcons.Regular.Th29,
            ElyonIcons.Regular.Th3,
            ElyonIcons.Regular.Th30,
            ElyonIcons.Regular.Th31,
            ElyonIcons.Regular.Th4,
            ElyonIcons.Regular.Th5,
            ElyonIcons.Regular.Th6,
            ElyonIcons.Regular.Th7,
            ElyonIcons.Regular.Th8,
            ElyonIcons.Regular.Th9,
            ElyonIcons.Regular.Theme,
            ElyonIcons.Regular.Timer,
            ElyonIcons.Regular.TopDownloads,
            ElyonIcons.Regular.Translate,
            ElyonIcons.Regular.Trim,
            ElyonIcons.Regular.Tune,
            ElyonIcons.Regular.Undo,
            ElyonIcons.Regular.Unlock,
            ElyonIcons.Regular.Unpin,
            ElyonIcons.Regular.Update,
            ElyonIcons.Regular.UploadCloud,
            ElyonIcons.Regular.VerticalSplit,
            ElyonIcons.Regular.VolumeOff,
            ElyonIcons.Regular.VolumeUp,
            ElyonIcons.Regular.Weeks,
            ElyonIcons.Regular.WorldClock,
            ElyonIcons.Regular.Years,
            ElyonIcons.Regular.ZoomOut,
        ),
        "Medium" to listOf(
            ElyonIcons.Medium.Add,
            ElyonIcons.Medium.AddCircle,
            ElyonIcons.Medium.AddFolder,
            ElyonIcons.Medium.Alarm,
            ElyonIcons.Medium.Album,
            ElyonIcons.Medium.All,
            ElyonIcons.Medium.Answer,
            ElyonIcons.Medium.AppRecording,
            ElyonIcons.Medium.Back,
            ElyonIcons.Medium.Background,
            ElyonIcons.Medium.Backup,
            ElyonIcons.Medium.BankCards,
            ElyonIcons.Medium.Blocklist,
            ElyonIcons.Medium.CallRecording,
            ElyonIcons.Medium.Carrier,
            ElyonIcons.Medium.ChevronBackward,
            ElyonIcons.Medium.ChevronForward,
            ElyonIcons.Medium.Clear,
            ElyonIcons.Medium.Close,
            ElyonIcons.Medium.Close2,
            ElyonIcons.Medium.CloudFill,
            ElyonIcons.Medium.Community,
            ElyonIcons.Medium.Contacts,
            ElyonIcons.Medium.ContactsBook,
            ElyonIcons.Medium.ContactsCircle,
            ElyonIcons.Medium.ConvertFile,
            ElyonIcons.Medium.Copy,
            ElyonIcons.Medium.Create,
            ElyonIcons.Medium.Cut,
            ElyonIcons.Medium.Delete,
            ElyonIcons.Medium.Download,
            ElyonIcons.Medium.Edit,
            ElyonIcons.Medium.Email,
            ElyonIcons.Medium.ExpandLess,
            ElyonIcons.Medium.ExpandMore,
            ElyonIcons.Medium.Favorites,
            ElyonIcons.Medium.FavoritesFill,
            ElyonIcons.Medium.File,
            ElyonIcons.Medium.FileDownloads,
            ElyonIcons.Medium.Filter,
            ElyonIcons.Medium.Folder,
            ElyonIcons.Medium.FolderFill,
            ElyonIcons.Medium.Forward,
            ElyonIcons.Medium.GridView,
            ElyonIcons.Medium.Help,
            ElyonIcons.Medium.Hide,
            ElyonIcons.Medium.Home,
            ElyonIcons.Medium.HorizontalSplit,
            ElyonIcons.Medium.Image,
            ElyonIcons.Medium.Import,
            ElyonIcons.Medium.Info,
            ElyonIcons.Medium.Layers,
            ElyonIcons.Medium.Link,
            ElyonIcons.Medium.ListView,
            ElyonIcons.Medium.Location,
            ElyonIcons.Medium.Lock,
            ElyonIcons.Medium.MapAlbum,
            ElyonIcons.Medium.Merge,
            ElyonIcons.Medium.Messages,
            ElyonIcons.Medium.Mic,
            ElyonIcons.Medium.MicSlash,
            ElyonIcons.Medium.MindMap,
            ElyonIcons.Medium.Months,
            ElyonIcons.Medium.More,
            ElyonIcons.Medium.MoreCircle,
            ElyonIcons.Medium.MoveFile,
            ElyonIcons.Medium.Music,
            ElyonIcons.Medium.Notes,
            ElyonIcons.Medium.NotesFill,
            ElyonIcons.Medium.Ok,
            ElyonIcons.Medium.Paste,
            ElyonIcons.Medium.Pause,
            ElyonIcons.Medium.Phone,
            ElyonIcons.Medium.Photos,
            ElyonIcons.Medium.Pin,
            ElyonIcons.Medium.Play,
            ElyonIcons.Medium.Playlist,
            ElyonIcons.Medium.Promotions,
            ElyonIcons.Medium.Recent,
            ElyonIcons.Medium.Recording,
            ElyonIcons.Medium.RecordingTape,
            ElyonIcons.Medium.Redo,
            ElyonIcons.Medium.Refresh,
            ElyonIcons.Medium.Remove,
            ElyonIcons.Medium.RemoveContact,
            ElyonIcons.Medium.Rename,
            ElyonIcons.Medium.Replace,
            ElyonIcons.Medium.Reply,
            ElyonIcons.Medium.ReplyAll,
            ElyonIcons.Medium.Report,
            ElyonIcons.Medium.Reset,
            ElyonIcons.Medium.RotateLeft,
            ElyonIcons.Medium.Scan,
            ElyonIcons.Medium.ScreenCapture,
            ElyonIcons.Medium.ScreenMirroring,
            ElyonIcons.Medium.Search,
            ElyonIcons.Medium.SearchDevice,
            ElyonIcons.Medium.SelectAll,
            ElyonIcons.Medium.Send,
            ElyonIcons.Medium.Settings,
            ElyonIcons.Medium.Share,
            ElyonIcons.Medium.Show,
            ElyonIcons.Medium.Sidebar,
            ElyonIcons.Medium.Sort,
            ElyonIcons.Medium.Stopwatch,
            ElyonIcons.Medium.Store,
            ElyonIcons.Medium.Tasks,
            ElyonIcons.Medium.Th1,
            ElyonIcons.Medium.Th10,
            ElyonIcons.Medium.Th11,
            ElyonIcons.Medium.Th12,
            ElyonIcons.Medium.Th13,
            ElyonIcons.Medium.Th14,
            ElyonIcons.Medium.Th15,
            ElyonIcons.Medium.Th16,
            ElyonIcons.Medium.Th17,
            ElyonIcons.Medium.Th18,
            ElyonIcons.Medium.Th19,
            ElyonIcons.Medium.Th2,
            ElyonIcons.Medium.Th20,
            ElyonIcons.Medium.Th21,
            ElyonIcons.Medium.Th22,
            ElyonIcons.Medium.Th23,
            ElyonIcons.Medium.Th24,
            ElyonIcons.Medium.Th25,
            ElyonIcons.Medium.Th26,
            ElyonIcons.Medium.Th27,
            ElyonIcons.Medium.Th28,
            ElyonIcons.Medium.Th29,
            ElyonIcons.Medium.Th3,
            ElyonIcons.Medium.Th30,
            ElyonIcons.Medium.Th31,
            ElyonIcons.Medium.Th4,
            ElyonIcons.Medium.Th5,
            ElyonIcons.Medium.Th6,
            ElyonIcons.Medium.Th7,
            ElyonIcons.Medium.Th8,
            ElyonIcons.Medium.Th9,
            ElyonIcons.Medium.Theme,
            ElyonIcons.Medium.Timer,
            ElyonIcons.Medium.TopDownloads,
            ElyonIcons.Medium.Translate,
            ElyonIcons.Medium.Trim,
            ElyonIcons.Medium.Tune,
            ElyonIcons.Medium.Undo,
            ElyonIcons.Medium.Unlock,
            ElyonIcons.Medium.Unpin,
            ElyonIcons.Medium.Update,
            ElyonIcons.Medium.UploadCloud,
            ElyonIcons.Medium.VerticalSplit,
            ElyonIcons.Medium.VolumeOff,
            ElyonIcons.Medium.VolumeUp,
            ElyonIcons.Medium.Weeks,
            ElyonIcons.Medium.WorldClock,
            ElyonIcons.Medium.Years,
            ElyonIcons.Medium.ZoomOut,
        ),
        "Demibold" to listOf(
            ElyonIcons.Demibold.Add,
            ElyonIcons.Demibold.AddCircle,
            ElyonIcons.Demibold.AddFolder,
            ElyonIcons.Demibold.Alarm,
            ElyonIcons.Demibold.Album,
            ElyonIcons.Demibold.All,
            ElyonIcons.Demibold.Answer,
            ElyonIcons.Demibold.AppRecording,
            ElyonIcons.Demibold.Back,
            ElyonIcons.Demibold.Background,
            ElyonIcons.Demibold.Backup,
            ElyonIcons.Demibold.BankCards,
            ElyonIcons.Demibold.Blocklist,
            ElyonIcons.Demibold.CallRecording,
            ElyonIcons.Demibold.Carrier,
            ElyonIcons.Demibold.ChevronBackward,
            ElyonIcons.Demibold.ChevronForward,
            ElyonIcons.Demibold.Clear,
            ElyonIcons.Demibold.Close,
            ElyonIcons.Demibold.Close2,
            ElyonIcons.Demibold.CloudFill,
            ElyonIcons.Demibold.Community,
            ElyonIcons.Demibold.Contacts,
            ElyonIcons.Demibold.ContactsBook,
            ElyonIcons.Demibold.ContactsCircle,
            ElyonIcons.Demibold.ConvertFile,
            ElyonIcons.Demibold.Copy,
            ElyonIcons.Demibold.Create,
            ElyonIcons.Demibold.Cut,
            ElyonIcons.Demibold.Delete,
            ElyonIcons.Demibold.Download,
            ElyonIcons.Demibold.Edit,
            ElyonIcons.Demibold.Email,
            ElyonIcons.Demibold.ExpandLess,
            ElyonIcons.Demibold.ExpandMore,
            ElyonIcons.Demibold.Favorites,
            ElyonIcons.Demibold.FavoritesFill,
            ElyonIcons.Demibold.File,
            ElyonIcons.Demibold.FileDownloads,
            ElyonIcons.Demibold.Filter,
            ElyonIcons.Demibold.Folder,
            ElyonIcons.Demibold.FolderFill,
            ElyonIcons.Demibold.Forward,
            ElyonIcons.Demibold.GridView,
            ElyonIcons.Demibold.Help,
            ElyonIcons.Demibold.Hide,
            ElyonIcons.Demibold.Home,
            ElyonIcons.Demibold.HorizontalSplit,
            ElyonIcons.Demibold.Image,
            ElyonIcons.Demibold.Import,
            ElyonIcons.Demibold.Info,
            ElyonIcons.Demibold.Layers,
            ElyonIcons.Demibold.Link,
            ElyonIcons.Demibold.ListView,
            ElyonIcons.Demibold.Location,
            ElyonIcons.Demibold.Lock,
            ElyonIcons.Demibold.MapAlbum,
            ElyonIcons.Demibold.Merge,
            ElyonIcons.Demibold.Messages,
            ElyonIcons.Demibold.Mic,
            ElyonIcons.Demibold.MicSlash,
            ElyonIcons.Demibold.MindMap,
            ElyonIcons.Demibold.Months,
            ElyonIcons.Demibold.More,
            ElyonIcons.Demibold.MoreCircle,
            ElyonIcons.Demibold.MoveFile,
            ElyonIcons.Demibold.Music,
            ElyonIcons.Demibold.Notes,
            ElyonIcons.Demibold.NotesFill,
            ElyonIcons.Demibold.Ok,
            ElyonIcons.Demibold.Paste,
            ElyonIcons.Demibold.Pause,
            ElyonIcons.Demibold.Phone,
            ElyonIcons.Demibold.Photos,
            ElyonIcons.Demibold.Pin,
            ElyonIcons.Demibold.Play,
            ElyonIcons.Demibold.Playlist,
            ElyonIcons.Demibold.Promotions,
            ElyonIcons.Demibold.Recent,
            ElyonIcons.Demibold.Recording,
            ElyonIcons.Demibold.RecordingTape,
            ElyonIcons.Demibold.Redo,
            ElyonIcons.Demibold.Refresh,
            ElyonIcons.Demibold.Remove,
            ElyonIcons.Demibold.RemoveContact,
            ElyonIcons.Demibold.Rename,
            ElyonIcons.Demibold.Replace,
            ElyonIcons.Demibold.Reply,
            ElyonIcons.Demibold.ReplyAll,
            ElyonIcons.Demibold.Report,
            ElyonIcons.Demibold.Reset,
            ElyonIcons.Demibold.RotateLeft,
            ElyonIcons.Demibold.Scan,
            ElyonIcons.Demibold.ScreenCapture,
            ElyonIcons.Demibold.ScreenMirroring,
            ElyonIcons.Demibold.Search,
            ElyonIcons.Demibold.SearchDevice,
            ElyonIcons.Demibold.SelectAll,
            ElyonIcons.Demibold.Send,
            ElyonIcons.Demibold.Settings,
            ElyonIcons.Demibold.Share,
            ElyonIcons.Demibold.Show,
            ElyonIcons.Demibold.Sidebar,
            ElyonIcons.Demibold.Sort,
            ElyonIcons.Demibold.Stopwatch,
            ElyonIcons.Demibold.Store,
            ElyonIcons.Demibold.Tasks,
            ElyonIcons.Demibold.Th1,
            ElyonIcons.Demibold.Th10,
            ElyonIcons.Demibold.Th11,
            ElyonIcons.Demibold.Th12,
            ElyonIcons.Demibold.Th13,
            ElyonIcons.Demibold.Th14,
            ElyonIcons.Demibold.Th15,
            ElyonIcons.Demibold.Th16,
            ElyonIcons.Demibold.Th17,
            ElyonIcons.Demibold.Th18,
            ElyonIcons.Demibold.Th19,
            ElyonIcons.Demibold.Th2,
            ElyonIcons.Demibold.Th20,
            ElyonIcons.Demibold.Th21,
            ElyonIcons.Demibold.Th22,
            ElyonIcons.Demibold.Th23,
            ElyonIcons.Demibold.Th24,
            ElyonIcons.Demibold.Th25,
            ElyonIcons.Demibold.Th26,
            ElyonIcons.Demibold.Th27,
            ElyonIcons.Demibold.Th28,
            ElyonIcons.Demibold.Th29,
            ElyonIcons.Demibold.Th3,
            ElyonIcons.Demibold.Th30,
            ElyonIcons.Demibold.Th31,
            ElyonIcons.Demibold.Th4,
            ElyonIcons.Demibold.Th5,
            ElyonIcons.Demibold.Th6,
            ElyonIcons.Demibold.Th7,
            ElyonIcons.Demibold.Th8,
            ElyonIcons.Demibold.Th9,
            ElyonIcons.Demibold.Theme,
            ElyonIcons.Demibold.Timer,
            ElyonIcons.Demibold.TopDownloads,
            ElyonIcons.Demibold.Translate,
            ElyonIcons.Demibold.Trim,
            ElyonIcons.Demibold.Tune,
            ElyonIcons.Demibold.Undo,
            ElyonIcons.Demibold.Unlock,
            ElyonIcons.Demibold.Unpin,
            ElyonIcons.Demibold.Update,
            ElyonIcons.Demibold.UploadCloud,
            ElyonIcons.Demibold.VerticalSplit,
            ElyonIcons.Demibold.VolumeOff,
            ElyonIcons.Demibold.VolumeUp,
            ElyonIcons.Demibold.Weeks,
            ElyonIcons.Demibold.WorldClock,
            ElyonIcons.Demibold.Years,
            ElyonIcons.Demibold.ZoomOut,
        ),
    )
