import { defineConfig } from 'vitepress'

const repository = 'https://github.com/vallind/elegant-ui'
const base = process.env.DOCS_BASE ?? '/elegant-ui/'

const englishSidebar = {
  '/guide/': [
    {
      text: 'Guide',
      items: [
        { text: 'Getting started', link: '/guide/getting-started' },
        { text: 'Installation', link: '/guide/installation' },
        { text: 'Local development', link: '/guide/local-development' },
        { text: 'Platform support', link: '/guide/platform-support' },
        { text: 'Design principles', link: '/guide/design-principles' },
        { text: 'Theme', link: '/guide/theme' },
        { text: 'Colors', link: '/guide/colors' },
        { text: 'Text styles', link: '/guide/textstyles' },
        { text: 'Best practices', link: '/guide/best-practices' },
        { text: 'Icons', link: '/guide/icons' },
        { text: 'Squircle', link: '/guide/squircle' },
        { text: 'Blur', link: '/guide/blur' },
        { text: 'Navigation', link: '/guide/navigation' },
        { text: 'ThemeController', link: '/guide/theme-controller' },
      ],
    },
  ],
  '/components/': [
        { text: 'Overview', link: '/components/' },
        { text: 'Foundations', items: [
          { text: 'Button', link: '/components/button' },
          { text: 'IconButton', link: '/components/icon-button' },
          { text: 'Avatar', link: '/components/avatar' },
          { text: 'Badge', link: '/components/badge' },
          { text: 'Divider', link: '/components/divider' },
          { text: 'Tag', link: '/components/tag' },
          { text: 'Tooltip', link: '/components/tooltip' },
          { text: 'ProgressIndicator', link: '/components/progress-indicator' },
          { text: 'Skeleton', link: '/components/skeleton' },
          { text: 'Alert', link: '/components/alert' },
          { text: 'AlertDialog', link: '/components/alert-dialog' },
          { text: 'Snackbar', link: '/components/snackbar' },
          { text: 'Toast', link: '/components/toast' },
          { text: 'Link', link: '/components/link' },
          { text: 'Label', link: '/components/label' },
          { text: 'Kbd', link: '/components/kbd' },
          { text: 'Surface', link: '/components/surface' },
          { text: 'Spinner', link: '/components/spinner' },
          { text: 'FloatingToolbar', link: '/components/floating-toolbar' },
          { text: 'ScrollBar', link: '/components/scroll-bar' },
          { text: 'Toolbar', link: '/components/toolbar' },
          { text: 'SmallTitle', link: '/components/small-title' },
          { text: 'EmptyState', link: '/components/empty-state' },
          { text: 'CloseButton', link: '/components/close-button' },
          { text: 'FloatingActionButton', link: '/components/floating-action-button' },
        ] },
        { text: 'Forms', items: [
          { text: 'Input', link: '/components/input' },
          { text: 'Textarea', link: '/components/textarea' },
          { text: 'NumberField', link: '/components/number-field' },
          { text: 'SearchBar', link: '/components/search-bar' },
          { text: 'InputOtp', link: '/components/input-otp' },
          { text: 'Select', link: '/components/select' },
          { text: 'Autocomplete', link: '/components/autocomplete' },
          { text: 'InputGroup', link: '/components/input-group' },
          { text: 'Checkbox', link: '/components/checkbox' },
          { text: 'Radio', link: '/components/radio' },
          { text: 'Switch', link: '/components/switch' },
          { text: 'Slider', link: '/components/slider' },
          { text: 'CheckboxGroup', link: '/components/checkbox-group' },
          { text: 'RadioGroup', link: '/components/radio-group' },
          { text: 'SwitchGroup', link: '/components/switch-group' },
          { text: 'ToggleButton', link: '/components/toggle-button' },
          { text: 'ButtonGroup', link: '/components/button-group' },
          { text: 'ColorPicker', link: '/components/color-picker' },
          { text: 'ColorPickerPanel', link: '/components/color-picker-panel' },
          { text: 'DatePicker', link: '/components/date-picker' },
          { text: 'DateRangePicker', link: '/components/date-range-picker' },
          { text: 'Calendar', link: '/components/calendar' },
          { text: 'NumberPicker', link: '/components/number-picker' },
          { text: 'Fieldset', link: '/components/fieldset' },
        ] },
        { text: 'Content', items: [
          { text: 'Card', link: '/components/card' },
          { text: 'List', link: '/components/list' },
          { text: 'ListItem', link: '/components/list-item' },
          { text: 'Table', link: '/components/table' },
          { text: 'Tabs', link: '/components/tabs' },
          { text: 'Accordion', link: '/components/accordion' },
          { text: 'Disclosure', link: '/components/disclosure' },
          { text: 'Description', link: '/components/description' },
          { text: 'Meter', link: '/components/meter' },
          { text: 'TagGroup', link: '/components/tag-group' },
          { text: 'ScrollShadow', link: '/components/scroll-shadow' },
          { text: 'PullToRefresh', link: '/components/pull-to-refresh' },
          { text: 'Scaffold', link: '/components/scaffold' },
        ] },
        { text: 'Navigation', items: [
          { text: 'Navbar', link: '/components/navbar' },
          { text: 'Sidebar', link: '/components/sidebar' },
          { text: 'Breadcrumb', link: '/components/breadcrumb' },
          { text: 'NavigationBar', link: '/components/navigation-bar' },
          { text: 'NavigationRail', link: '/components/navigation-rail' },
          { text: 'Pagination', link: '/components/pagination' },
        ] },
        { text: 'Overlays', items: [
          { text: 'Modal', link: '/components/modal' },
          { text: 'BottomSheet', link: '/components/bottom-sheet' },
          { text: 'Drawer', link: '/components/drawer' },
          { text: 'Popover', link: '/components/popover' },
          { text: 'Menu', link: '/components/menu' },
          { text: 'ListPopup', link: '/components/list-popup' },
          { text: 'CascadingMenu', link: '/components/cascading-menu' },
        ] },
        { text: 'Settings', items: [
          { text: 'SwitchPreference', link: '/components/switch-preference' },
          { text: 'CheckboxPreference', link: '/components/checkbox-preference' },
          { text: 'RadioPreference', link: '/components/radio-preference' },
          { text: 'SliderPreference', link: '/components/slider-preference' },
          { text: 'ArrowPreference', link: '/components/arrow-preference' },
          { text: 'BasicComponent', link: '/components/basic-component' },
        ] },
  ],
}

const chineseSidebar = {
  '/zh_CN/guide/': [
    {
      text: '指南',
      items: [
        { text: '快速开始', link: '/zh_CN/guide/getting-started' },
        { text: '安装与依赖', link: '/zh_CN/guide/installation' },
        { text: '本地联调', link: '/zh_CN/guide/local-development' },
        { text: '平台支持', link: '/zh_CN/guide/platform-support' },
        { text: '设计原则', link: '/zh_CN/guide/design-principles' },
        { text: '主题', link: '/zh_CN/guide/theme' },
        { text: '颜色', link: '/zh_CN/guide/colors' },
        { text: '文本样式', link: '/zh_CN/guide/textstyles' },
        { text: '最佳实践', link: '/zh_CN/guide/best-practices' },
        { text: 'Icons 图标', link: '/zh_CN/guide/icons' },
        { text: 'Squircle 超椭圆', link: '/zh_CN/guide/squircle' },
        { text: 'Blur 模糊', link: '/zh_CN/guide/blur' },
        { text: 'Navigation 导航', link: '/zh_CN/guide/navigation' },
        { text: 'ThemeController 动态取色', link: '/zh_CN/guide/theme-controller' },
      ],
    },
  ],
  '/zh_CN/components/': [
        { text: '总览', link: '/zh_CN/components/' },
        { text: '基础组件', items: [
          { text: 'Button 按钮', link: '/zh_CN/components/button' },
          { text: 'IconButton 图标按钮', link: '/zh_CN/components/icon-button' },
          { text: 'Avatar 头像', link: '/zh_CN/components/avatar' },
          { text: 'Badge 徽标', link: '/zh_CN/components/badge' },
          { text: 'Divider 分割线', link: '/zh_CN/components/divider' },
          { text: 'Tag 标签', link: '/zh_CN/components/tag' },
          { text: 'Tooltip 提示', link: '/zh_CN/components/tooltip' },
          { text: 'ProgressIndicator 进度指示', link: '/zh_CN/components/progress-indicator' },
          { text: 'Skeleton 骨架屏', link: '/zh_CN/components/skeleton' },
          { text: 'Alert 警告条', link: '/zh_CN/components/alert' },
          { text: 'AlertDialog 确认弹窗', link: '/zh_CN/components/alert-dialog' },
          { text: 'Snackbar 轻提示', link: '/zh_CN/components/snackbar' },
          { text: 'Toast 顶部提示', link: '/zh_CN/components/toast' },
          { text: 'Link 链接', link: '/zh_CN/components/link' },
          { text: 'Label 标签', link: '/zh_CN/components/label' },
          { text: 'Kbd 按键', link: '/zh_CN/components/kbd' },
          { text: 'Surface 表面', link: '/zh_CN/components/surface' },
          { text: 'Spinner 加载圈', link: '/zh_CN/components/spinner' },
          { text: 'FloatingToolbar 浮动工具栏', link: '/zh_CN/components/floating-toolbar' },
          { text: 'ScrollBar 滚动条', link: '/zh_CN/components/scroll-bar' },
          { text: 'Toolbar 工具栏', link: '/zh_CN/components/toolbar' },
          { text: 'SmallTitle 分组标题', link: '/zh_CN/components/small-title' },
          { text: 'EmptyState 空状态', link: '/zh_CN/components/empty-state' },
          { text: 'CloseButton 关闭按钮', link: '/zh_CN/components/close-button' },
          { text: 'FloatingActionButton 悬浮按钮', link: '/zh_CN/components/floating-action-button' },
        ] },
        { text: '表单组件', items: [
          { text: 'Input 输入框', link: '/zh_CN/components/input' },
          { text: 'Textarea 多行输入', link: '/zh_CN/components/textarea' },
          { text: 'NumberField 数字输入', link: '/zh_CN/components/number-field' },
          { text: 'SearchBar 搜索栏', link: '/zh_CN/components/search-bar' },
          { text: 'InputOtp 验证码输入', link: '/zh_CN/components/input-otp' },
          { text: 'Select 选择器', link: '/zh_CN/components/select' },
          { text: 'Autocomplete 自动补全', link: '/zh_CN/components/autocomplete' },
          { text: 'InputGroup 输入组', link: '/zh_CN/components/input-group' },
          { text: 'Checkbox 复选框', link: '/zh_CN/components/checkbox' },
          { text: 'Radio 单选', link: '/zh_CN/components/radio' },
          { text: 'Switch 开关', link: '/zh_CN/components/switch' },
          { text: 'Slider 滑块', link: '/zh_CN/components/slider' },
          { text: 'CheckboxGroup 复选组', link: '/zh_CN/components/checkbox-group' },
          { text: 'RadioGroup 单选组', link: '/zh_CN/components/radio-group' },
          { text: 'SwitchGroup 开关组', link: '/zh_CN/components/switch-group' },
          { text: 'ToggleButton 切换按钮', link: '/zh_CN/components/toggle-button' },
          { text: 'ButtonGroup 按钮组', link: '/zh_CN/components/button-group' },
          { text: 'ColorPicker 取色器', link: '/zh_CN/components/color-picker' },
          { text: 'ColorPickerPanel 取色面板', link: '/zh_CN/components/color-picker-panel' },
          { text: 'DatePicker 日期选择', link: '/zh_CN/components/date-picker' },
          { text: 'DateRangePicker 日期范围', link: '/zh_CN/components/date-range-picker' },
          { text: 'Calendar 日历', link: '/zh_CN/components/calendar' },
          { text: 'NumberPicker 数字选择器', link: '/zh_CN/components/number-picker' },
          { text: 'Fieldset 字段分组', link: '/zh_CN/components/fieldset' },
        ] },
        { text: '内容组件', items: [
          { text: 'Card 卡片', link: '/zh_CN/components/card' },
          { text: 'List 列表', link: '/zh_CN/components/list' },
          { text: 'ListItem 列表项', link: '/zh_CN/components/list-item' },
          { text: 'Table 表格', link: '/zh_CN/components/table' },
          { text: 'Tabs 标签页', link: '/zh_CN/components/tabs' },
          { text: 'Accordion 手风琴', link: '/zh_CN/components/accordion' },
          { text: 'Disclosure 展开块', link: '/zh_CN/components/disclosure' },
          { text: 'Description 描述列表', link: '/zh_CN/components/description' },
          { text: 'Meter 仪表', link: '/zh_CN/components/meter' },
          { text: 'TagGroup 标签组', link: '/zh_CN/components/tag-group' },
          { text: 'ScrollShadow 滚动阴影', link: '/zh_CN/components/scroll-shadow' },
          { text: 'PullToRefresh 下拉刷新', link: '/zh_CN/components/pull-to-refresh' },
          { text: 'Scaffold 应用外壳', link: '/zh_CN/components/scaffold' },
        ] },
        { text: '导航组件', items: [
          { text: 'Navbar 导航栏', link: '/zh_CN/components/navbar' },
          { text: 'Sidebar 侧边栏', link: '/zh_CN/components/sidebar' },
          { text: 'Breadcrumb 面包屑', link: '/zh_CN/components/breadcrumb' },
          { text: 'NavigationBar 底部导航', link: '/zh_CN/components/navigation-bar' },
          { text: 'NavigationRail 侧边导航栏', link: '/zh_CN/components/navigation-rail' },
          { text: 'Pagination 分页', link: '/zh_CN/components/pagination' },
        ] },
        { text: '浮层组件', items: [
          { text: 'Modal 弹窗', link: '/zh_CN/components/modal' },
          { text: 'BottomSheet 底部面板', link: '/zh_CN/components/bottom-sheet' },
          { text: 'Drawer 抽屉', link: '/zh_CN/components/drawer' },
          { text: 'Popover 浮层', link: '/zh_CN/components/popover' },
          { text: 'Menu 菜单', link: '/zh_CN/components/menu' },
          { text: 'ListPopup 列表弹出', link: '/zh_CN/components/list-popup' },
          { text: 'CascadingMenu 级联菜单', link: '/zh_CN/components/cascading-menu' },
        ] },
        { text: '设置组件', items: [
          { text: 'SwitchPreference 开关设置', link: '/zh_CN/components/switch-preference' },
          { text: 'CheckboxPreference 复选设置', link: '/zh_CN/components/checkbox-preference' },
          { text: 'RadioPreference 单选设置', link: '/zh_CN/components/radio-preference' },
          { text: 'SliderPreference 滑块设置', link: '/zh_CN/components/slider-preference' },
          { text: 'ArrowPreference 箭头设置', link: '/zh_CN/components/arrow-preference' },
          { text: 'BasicComponent 基础行', link: '/zh_CN/components/basic-component' },
        ] },
  ],
}

export default defineConfig({
  title: 'Elegant UI',
  description: 'Refined Compose Multiplatform components for Android, Desktop JVM, and Web/Wasm.',
  base,
  cleanUrls: true,
  lastUpdated: true,
  head: [
    ['link', { rel: 'icon', type: 'image/svg+xml', href: `${base}logo.svg` }],
    ['meta', { name: 'theme-color', content: '#6d5dfc' }],
  ],
  locales: {
    root: {
      label: 'English',
      lang: 'en-US',
      themeConfig: {
        nav: [
          { text: 'Guide', link: '/guide/getting-started' },
          { text: 'Components', link: '/components/' },
          { text: 'GitHub', link: repository },
        ],
        sidebar: englishSidebar,
        editLink: {
          pattern: `${repository}/edit/main/docs/:path`,
          text: 'Edit this page on GitHub',
        },
        outline: {
          level: [2, 3],
          label: 'On this page',
        },
        langMenuLabel: 'Change language',
        sidebarMenuLabel: 'Menu',
        returnToTopLabel: 'Return to top',
      },
    },
    zh_CN: {
      label: '简体中文',
      lang: 'zh-CN',
      link: '/zh_CN/',
      title: 'Elegant UI',
      description: '面向 Android、Desktop JVM 与 Web/Wasm 的精致 Compose Multiplatform 组件库。',
      themeConfig: {
        nav: [
          { text: '指南', link: '/zh_CN/guide/getting-started' },
          { text: '组件', link: '/zh_CN/components/' },
          { text: 'GitHub', link: repository },
        ],
        sidebar: chineseSidebar,
        editLink: {
          pattern: `${repository}/edit/main/docs/:path`,
          text: '在 GitHub 上编辑此页',
        },
        outline: {
          level: [2, 3],
          label: '页面导航',
        },
        langMenuLabel: '切换语言',
        sidebarMenuLabel: '菜单',
        returnToTopLabel: '返回顶部',
        docFooter: {
          prev: '上一页',
          next: '下一页',
        },
        lastUpdated: {
          text: '最后更新',
        },
      },
    },
  },
  themeConfig: {
    logo: `${base}logo.svg`,
    siteTitle: 'Elegant UI',
    search: { provider: 'local' },
    socialLinks: [
      { icon: 'github', link: repository },
    ],
    footer: {
      message: 'Elegant Android components for Kotlin and Jetpack Compose.',
      copyright: 'Copyright © 2026 Elegant UI contributors',
    },
  },
})
